//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteColegioSWNet.ServicioMateriaSW {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class materia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private int gradoField;
        
        private double intensidadHorariaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int grado {
            get {
                return this.gradoField;
            }
            set {
                this.gradoField = value;
                this.RaisePropertyChanged("grado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double intensidadHoraria {
            get {
                return this.intensidadHorariaField;
            }
            set {
                this.intensidadHorariaField = value;
                this.RaisePropertyChanged("intensidadHoraria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosWeb/", ConfigurationName="ServicioMateriaSW.ServicioMateriaSW")]
    public interface ServicioMateriaSW {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMateriaSW/darMateriaPorCodigoRequest", ReplyAction="http://serviciosWeb/ServicioMateriaSW/darMateriaPorCodigoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMateriaSW.Exception), Action="http://serviciosWeb/ServicioMateriaSW/darMateriaPorCodigo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoResponse darMateriaPorCodigo(ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMateriaSW/darMateriaPorCodigoRequest", ReplyAction="http://serviciosWeb/ServicioMateriaSW/darMateriaPorCodigoResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoResponse> darMateriaPorCodigoAsync(ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMateriaSW/darMateriasPorGradoRequest", ReplyAction="http://serviciosWeb/ServicioMateriaSW/darMateriasPorGradoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMateriaSW.Exception), Action="http://serviciosWeb/ServicioMateriaSW/darMateriasPorGrado/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoResponse darMateriasPorGrado(ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMateriaSW/darMateriasPorGradoRequest", ReplyAction="http://serviciosWeb/ServicioMateriaSW/darMateriasPorGradoResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoResponse> darMateriasPorGradoAsync(ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMateriaSW/darMateriasRequest", ReplyAction="http://serviciosWeb/ServicioMateriaSW/darMateriasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMateriaSW.Exception), Action="http://serviciosWeb/ServicioMateriaSW/darMaterias/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMateriaSW.darMateriasResponse darMaterias(ClienteColegioSWNet.ServicioMateriaSW.darMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMateriaSW/darMateriasRequest", ReplyAction="http://serviciosWeb/ServicioMateriaSW/darMateriasResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriasResponse> darMateriasAsync(ClienteColegioSWNet.ServicioMateriaSW.darMateriasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMateriaPorCodigo", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMateriaPorCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public darMateriaPorCodigoRequest() {
        }
        
        public darMateriaPorCodigoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMateriaPorCodigoResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMateriaPorCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMateriaSW.materia @return;
        
        public darMateriaPorCodigoResponse() {
        }
        
        public darMateriaPorCodigoResponse(ClienteColegioSWNet.ServicioMateriaSW.materia @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMateriasPorGrado", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMateriasPorGradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public darMateriasPorGradoRequest() {
        }
        
        public darMateriasPorGradoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMateriasPorGradoResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMateriasPorGradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMateriaSW.materia[] @return;
        
        public darMateriasPorGradoResponse() {
        }
        
        public darMateriasPorGradoResponse(ClienteColegioSWNet.ServicioMateriaSW.materia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMaterias", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMateriasRequest {
        
        public darMateriasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMateriasResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMateriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMateriaSW.materia[] @return;
        
        public darMateriasResponse() {
        }
        
        public darMateriasResponse(ClienteColegioSWNet.ServicioMateriaSW.materia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioMateriaSWChannel : ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMateriaSWClient : System.ServiceModel.ClientBase<ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW>, ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW {
        
        public ServicioMateriaSWClient() {
        }
        
        public ServicioMateriaSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMateriaSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMateriaSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMateriaSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoResponse ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW.darMateriaPorCodigo(ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoRequest request) {
            return base.Channel.darMateriaPorCodigo(request);
        }
        
        public ClienteColegioSWNet.ServicioMateriaSW.materia darMateriaPorCodigo(int arg0) {
            ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoRequest inValue = new ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoResponse retVal = ((ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW)(this)).darMateriaPorCodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoResponse> ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW.darMateriaPorCodigoAsync(ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoRequest request) {
            return base.Channel.darMateriaPorCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoResponse> darMateriaPorCodigoAsync(int arg0) {
            ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoRequest inValue = new ClienteColegioSWNet.ServicioMateriaSW.darMateriaPorCodigoRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW)(this)).darMateriaPorCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoResponse ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW.darMateriasPorGrado(ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoRequest request) {
            return base.Channel.darMateriasPorGrado(request);
        }
        
        public ClienteColegioSWNet.ServicioMateriaSW.materia[] darMateriasPorGrado(int arg0) {
            ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoRequest inValue = new ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoResponse retVal = ((ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW)(this)).darMateriasPorGrado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoResponse> ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW.darMateriasPorGradoAsync(ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoRequest request) {
            return base.Channel.darMateriasPorGradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoResponse> darMateriasPorGradoAsync(int arg0) {
            ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoRequest inValue = new ClienteColegioSWNet.ServicioMateriaSW.darMateriasPorGradoRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW)(this)).darMateriasPorGradoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMateriaSW.darMateriasResponse ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW.darMaterias(ClienteColegioSWNet.ServicioMateriaSW.darMateriasRequest request) {
            return base.Channel.darMaterias(request);
        }
        
        public ClienteColegioSWNet.ServicioMateriaSW.materia[] darMaterias() {
            ClienteColegioSWNet.ServicioMateriaSW.darMateriasRequest inValue = new ClienteColegioSWNet.ServicioMateriaSW.darMateriasRequest();
            ClienteColegioSWNet.ServicioMateriaSW.darMateriasResponse retVal = ((ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW)(this)).darMaterias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriasResponse> ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW.darMateriasAsync(ClienteColegioSWNet.ServicioMateriaSW.darMateriasRequest request) {
            return base.Channel.darMateriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMateriaSW.darMateriasResponse> darMateriasAsync() {
            ClienteColegioSWNet.ServicioMateriaSW.darMateriasRequest inValue = new ClienteColegioSWNet.ServicioMateriaSW.darMateriasRequest();
            return ((ClienteColegioSWNet.ServicioMateriaSW.ServicioMateriaSW)(this)).darMateriasAsync(inValue);
        }
    }
}
