//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteColegioSWNet.ServicioExtraSW {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosWeb/", ConfigurationName="ServicioExtraSW.ServiciosExtraSW")]
    public interface ServiciosExtraSW {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServiciosExtraSW/darCantidadMateriasPorGradoCursandoRequest", ReplyAction="http://serviciosWeb/ServiciosExtraSW/darCantidadMateriasPorGradoCursandoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioExtraSW.Exception), Action="http://serviciosWeb/ServiciosExtraSW/darCantidadMateriasPorGradoCursando/Fault/Ex" +
            "ception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoResponse darCantidadMateriasPorGradoCursando(ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServiciosExtraSW/darCantidadMateriasPorGradoCursandoRequest", ReplyAction="http://serviciosWeb/ServiciosExtraSW/darCantidadMateriasPorGradoCursandoResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoResponse> darCantidadMateriasPorGradoCursandoAsync(ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServiciosExtraSW/cantidadEstudiantesRegistradosRequest", ReplyAction="http://serviciosWeb/ServiciosExtraSW/cantidadEstudiantesRegistradosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosResponse cantidadEstudiantesRegistrados(ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServiciosExtraSW/cantidadEstudiantesRegistradosRequest", ReplyAction="http://serviciosWeb/ServiciosExtraSW/cantidadEstudiantesRegistradosResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosResponse> cantidadEstudiantesRegistradosAsync(ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServiciosExtraSW/cantidadMateriasRegistradasRequest", ReplyAction="http://serviciosWeb/ServiciosExtraSW/cantidadMateriasRegistradasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasResponse cantidadMateriasRegistradas(ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServiciosExtraSW/cantidadMateriasRegistradasRequest", ReplyAction="http://serviciosWeb/ServiciosExtraSW/cantidadMateriasRegistradasResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasResponse> cantidadMateriasRegistradasAsync(ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServiciosExtraSW/cantidadMatriculasRegistradasRequest", ReplyAction="http://serviciosWeb/ServiciosExtraSW/cantidadMatriculasRegistradasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasResponse cantidadMatriculasRegistradas(ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServiciosExtraSW/cantidadMatriculasRegistradasRequest", ReplyAction="http://serviciosWeb/ServiciosExtraSW/cantidadMatriculasRegistradasResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasResponse> cantidadMatriculasRegistradasAsync(ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darCantidadMateriasPorGradoCursando", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darCantidadMateriasPorGradoCursandoRequest {
        
        public darCantidadMateriasPorGradoCursandoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darCantidadMateriasPorGradoCursandoResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darCantidadMateriasPorGradoCursandoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] @return;
        
        public darCantidadMateriasPorGradoCursandoResponse() {
        }
        
        public darCantidadMateriasPorGradoCursandoResponse(System.Nullable<int>[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cantidadEstudiantesRegistrados", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class cantidadEstudiantesRegistradosRequest {
        
        public cantidadEstudiantesRegistradosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cantidadEstudiantesRegistradosResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class cantidadEstudiantesRegistradosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cantidadEstudiantesRegistradosResponse() {
        }
        
        public cantidadEstudiantesRegistradosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cantidadMateriasRegistradas", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class cantidadMateriasRegistradasRequest {
        
        public cantidadMateriasRegistradasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cantidadMateriasRegistradasResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class cantidadMateriasRegistradasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cantidadMateriasRegistradasResponse() {
        }
        
        public cantidadMateriasRegistradasResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cantidadMatriculasRegistradas", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class cantidadMatriculasRegistradasRequest {
        
        public cantidadMatriculasRegistradasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cantidadMatriculasRegistradasResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class cantidadMatriculasRegistradasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cantidadMatriculasRegistradasResponse() {
        }
        
        public cantidadMatriculasRegistradasResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosExtraSWChannel : ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosExtraSWClient : System.ServiceModel.ClientBase<ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW>, ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW {
        
        public ServiciosExtraSWClient() {
        }
        
        public ServiciosExtraSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosExtraSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosExtraSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosExtraSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoResponse ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW.darCantidadMateriasPorGradoCursando(ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoRequest request) {
            return base.Channel.darCantidadMateriasPorGradoCursando(request);
        }
        
        public System.Nullable<int>[] darCantidadMateriasPorGradoCursando() {
            ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoRequest inValue = new ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoRequest();
            ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoResponse retVal = ((ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW)(this)).darCantidadMateriasPorGradoCursando(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoResponse> ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW.darCantidadMateriasPorGradoCursandoAsync(ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoRequest request) {
            return base.Channel.darCantidadMateriasPorGradoCursandoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoResponse> darCantidadMateriasPorGradoCursandoAsync() {
            ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoRequest inValue = new ClienteColegioSWNet.ServicioExtraSW.darCantidadMateriasPorGradoCursandoRequest();
            return ((ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW)(this)).darCantidadMateriasPorGradoCursandoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosResponse ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW.cantidadEstudiantesRegistrados(ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosRequest request) {
            return base.Channel.cantidadEstudiantesRegistrados(request);
        }
        
        public int cantidadEstudiantesRegistrados() {
            ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosRequest inValue = new ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosRequest();
            ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosResponse retVal = ((ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW)(this)).cantidadEstudiantesRegistrados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosResponse> ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW.cantidadEstudiantesRegistradosAsync(ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosRequest request) {
            return base.Channel.cantidadEstudiantesRegistradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosResponse> cantidadEstudiantesRegistradosAsync() {
            ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosRequest inValue = new ClienteColegioSWNet.ServicioExtraSW.cantidadEstudiantesRegistradosRequest();
            return ((ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW)(this)).cantidadEstudiantesRegistradosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasResponse ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW.cantidadMateriasRegistradas(ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasRequest request) {
            return base.Channel.cantidadMateriasRegistradas(request);
        }
        
        public int cantidadMateriasRegistradas() {
            ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasRequest inValue = new ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasRequest();
            ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasResponse retVal = ((ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW)(this)).cantidadMateriasRegistradas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasResponse> ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW.cantidadMateriasRegistradasAsync(ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasRequest request) {
            return base.Channel.cantidadMateriasRegistradasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasResponse> cantidadMateriasRegistradasAsync() {
            ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasRequest inValue = new ClienteColegioSWNet.ServicioExtraSW.cantidadMateriasRegistradasRequest();
            return ((ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW)(this)).cantidadMateriasRegistradasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasResponse ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW.cantidadMatriculasRegistradas(ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasRequest request) {
            return base.Channel.cantidadMatriculasRegistradas(request);
        }
        
        public int cantidadMatriculasRegistradas() {
            ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasRequest inValue = new ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasRequest();
            ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasResponse retVal = ((ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW)(this)).cantidadMatriculasRegistradas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasResponse> ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW.cantidadMatriculasRegistradasAsync(ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasRequest request) {
            return base.Channel.cantidadMatriculasRegistradasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasResponse> cantidadMatriculasRegistradasAsync() {
            ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasRequest inValue = new ClienteColegioSWNet.ServicioExtraSW.cantidadMatriculasRegistradasRequest();
            return ((ClienteColegioSWNet.ServicioExtraSW.ServiciosExtraSW)(this)).cantidadMatriculasRegistradasAsync(inValue);
        }
    }
}
