//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteColegioSWNet.ServicioEstudianteSW {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class estudiante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string correoField;
        
        private string direccionField;
        
        private string documentoIdentificacionField;
        
        private string epsField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int generoField;
        
        private string nombresField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string documentoIdentificacion {
            get {
                return this.documentoIdentificacionField;
            }
            set {
                this.documentoIdentificacionField = value;
                this.RaisePropertyChanged("documentoIdentificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string eps {
            get {
                return this.epsField;
            }
            set {
                this.epsField = value;
                this.RaisePropertyChanged("eps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosWeb/", ConfigurationName="ServicioEstudianteSW.ServicioEstudianteSW")]
    public interface ServicioEstudianteSW {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/buscarEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/buscarEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioEstudianteSW.Exception), Action="http://serviciosWeb/ServicioEstudianteSW/buscarEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteResponse buscarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/buscarEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/buscarEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteResponse> buscarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/darGradoEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/darGradoEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioEstudianteSW.Exception), Action="http://serviciosWeb/ServicioEstudianteSW/darGradoEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteResponse darGradoEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/darGradoEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/darGradoEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteResponse> darGradoEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/eliminarEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/eliminarEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioEstudianteSW.Exception), Action="http://serviciosWeb/ServicioEstudianteSW/eliminarEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteResponse eliminarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/eliminarEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/eliminarEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteResponse> eliminarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/actualizarEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/actualizarEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioEstudianteSW.Exception), Action="http://serviciosWeb/ServicioEstudianteSW/actualizarEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteResponse actualizarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/actualizarEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/actualizarEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteResponse> actualizarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/cantidadEstudiantesPorGeneroRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/cantidadEstudiantesPorGeneroResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioEstudianteSW.Exception), Action="http://serviciosWeb/ServicioEstudianteSW/cantidadEstudiantesPorGenero/Fault/Excep" +
            "tion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroResponse cantidadEstudiantesPorGenero(ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/cantidadEstudiantesPorGeneroRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/cantidadEstudiantesPorGeneroResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroResponse> cantidadEstudiantesPorGeneroAsync(ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesPorNombreRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesPorNombreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioEstudianteSW.Exception), Action="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesPorNombre/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreResponse darEstudiantesPorNombre(ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesPorNombreRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesPorNombreResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreResponse> darEstudiantesPorNombreAsync(ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/insertarEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/insertarEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioEstudianteSW.Exception), Action="http://serviciosWeb/ServicioEstudianteSW/insertarEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteResponse insertarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/insertarEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/insertarEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteResponse> insertarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioEstudianteSW.Exception), Action="http://serviciosWeb/ServicioEstudianteSW/darEstudiantes/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesResponse darEstudiantes(ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesRequest", ReplyAction="http://serviciosWeb/ServicioEstudianteSW/darEstudiantesResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesResponse> darEstudiantesAsync(ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public buscarEstudianteRequest() {
        }
        
        public buscarEstudianteRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarEstudianteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioEstudianteSW.estudiante @return;
        
        public buscarEstudianteResponse() {
        }
        
        public buscarEstudianteResponse(ClienteColegioSWNet.ServicioEstudianteSW.estudiante @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darGradoEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darGradoEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public darGradoEstudianteRequest() {
        }
        
        public darGradoEstudianteRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darGradoEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darGradoEstudianteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public darGradoEstudianteResponse() {
        }
        
        public darGradoEstudianteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class eliminarEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public eliminarEstudianteRequest() {
        }
        
        public eliminarEstudianteRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class eliminarEstudianteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarEstudianteResponse() {
        }
        
        public eliminarEstudianteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class actualizarEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioEstudianteSW.estudiante arg1;
        
        public actualizarEstudianteRequest() {
        }
        
        public actualizarEstudianteRequest(string arg0, ClienteColegioSWNet.ServicioEstudianteSW.estudiante arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class actualizarEstudianteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public actualizarEstudianteResponse() {
        }
        
        public actualizarEstudianteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cantidadEstudiantesPorGenero", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class cantidadEstudiantesPorGeneroRequest {
        
        public cantidadEstudiantesPorGeneroRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cantidadEstudiantesPorGeneroResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class cantidadEstudiantesPorGeneroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] @return;
        
        public cantidadEstudiantesPorGeneroResponse() {
        }
        
        public cantidadEstudiantesPorGeneroResponse(System.Nullable<int>[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darEstudiantesPorNombre", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darEstudiantesPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public darEstudiantesPorNombreRequest() {
        }
        
        public darEstudiantesPorNombreRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darEstudiantesPorNombreResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darEstudiantesPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioEstudianteSW.estudiante[] @return;
        
        public darEstudiantesPorNombreResponse() {
        }
        
        public darEstudiantesPorNombreResponse(ClienteColegioSWNet.ServicioEstudianteSW.estudiante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class insertarEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioEstudianteSW.estudiante arg0;
        
        public insertarEstudianteRequest() {
        }
        
        public insertarEstudianteRequest(ClienteColegioSWNet.ServicioEstudianteSW.estudiante arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class insertarEstudianteResponse {
        
        public insertarEstudianteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darEstudiantes", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darEstudiantesRequest {
        
        public darEstudiantesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darEstudiantesResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darEstudiantesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioEstudianteSW.estudiante[] @return;
        
        public darEstudiantesResponse() {
        }
        
        public darEstudiantesResponse(ClienteColegioSWNet.ServicioEstudianteSW.estudiante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioEstudianteSWChannel : ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEstudianteSWClient : System.ServiceModel.ClientBase<ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW>, ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW {
        
        public ServicioEstudianteSWClient() {
        }
        
        public ServicioEstudianteSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEstudianteSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstudianteSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstudianteSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteResponse ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.buscarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteRequest request) {
            return base.Channel.buscarEstudiante(request);
        }
        
        public ClienteColegioSWNet.ServicioEstudianteSW.estudiante buscarEstudiante(string arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).buscarEstudiante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteResponse> ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.buscarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteRequest request) {
            return base.Channel.buscarEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteResponse> buscarEstudianteAsync(string arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.buscarEstudianteRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).buscarEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteResponse ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.darGradoEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteRequest request) {
            return base.Channel.darGradoEstudiante(request);
        }
        
        public int darGradoEstudiante(string arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).darGradoEstudiante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteResponse> ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.darGradoEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteRequest request) {
            return base.Channel.darGradoEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteResponse> darGradoEstudianteAsync(string arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.darGradoEstudianteRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).darGradoEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteResponse ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.eliminarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteRequest request) {
            return base.Channel.eliminarEstudiante(request);
        }
        
        public bool eliminarEstudiante(string arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).eliminarEstudiante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteResponse> ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.eliminarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteRequest request) {
            return base.Channel.eliminarEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteResponse> eliminarEstudianteAsync(string arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.eliminarEstudianteRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).eliminarEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteResponse ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.actualizarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteRequest request) {
            return base.Channel.actualizarEstudiante(request);
        }
        
        public bool actualizarEstudiante(string arg0, ClienteColegioSWNet.ServicioEstudianteSW.estudiante arg1) {
            ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).actualizarEstudiante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteResponse> ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.actualizarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteRequest request) {
            return base.Channel.actualizarEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteResponse> actualizarEstudianteAsync(string arg0, ClienteColegioSWNet.ServicioEstudianteSW.estudiante arg1) {
            ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.actualizarEstudianteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).actualizarEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroResponse ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.cantidadEstudiantesPorGenero(ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroRequest request) {
            return base.Channel.cantidadEstudiantesPorGenero(request);
        }
        
        public System.Nullable<int>[] cantidadEstudiantesPorGenero() {
            ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroRequest();
            ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroResponse retVal = ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).cantidadEstudiantesPorGenero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroResponse> ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.cantidadEstudiantesPorGeneroAsync(ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroRequest request) {
            return base.Channel.cantidadEstudiantesPorGeneroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroResponse> cantidadEstudiantesPorGeneroAsync() {
            ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.cantidadEstudiantesPorGeneroRequest();
            return ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).cantidadEstudiantesPorGeneroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreResponse ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.darEstudiantesPorNombre(ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreRequest request) {
            return base.Channel.darEstudiantesPorNombre(request);
        }
        
        public ClienteColegioSWNet.ServicioEstudianteSW.estudiante[] darEstudiantesPorNombre(string arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreResponse retVal = ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).darEstudiantesPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreResponse> ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.darEstudiantesPorNombreAsync(ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreRequest request) {
            return base.Channel.darEstudiantesPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreResponse> darEstudiantesPorNombreAsync(string arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesPorNombreRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).darEstudiantesPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteResponse ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.insertarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteRequest request) {
            return base.Channel.insertarEstudiante(request);
        }
        
        public void insertarEstudiante(ClienteColegioSWNet.ServicioEstudianteSW.estudiante arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).insertarEstudiante(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteResponse> ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.insertarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteRequest request) {
            return base.Channel.insertarEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteResponse> insertarEstudianteAsync(ClienteColegioSWNet.ServicioEstudianteSW.estudiante arg0) {
            ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.insertarEstudianteRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).insertarEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesResponse ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.darEstudiantes(ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesRequest request) {
            return base.Channel.darEstudiantes(request);
        }
        
        public ClienteColegioSWNet.ServicioEstudianteSW.estudiante[] darEstudiantes() {
            ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesRequest();
            ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesResponse retVal = ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).darEstudiantes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesResponse> ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW.darEstudiantesAsync(ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesRequest request) {
            return base.Channel.darEstudiantesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesResponse> darEstudiantesAsync() {
            ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesRequest inValue = new ClienteColegioSWNet.ServicioEstudianteSW.darEstudiantesRequest();
            return ((ClienteColegioSWNet.ServicioEstudianteSW.ServicioEstudianteSW)(this)).darEstudiantesAsync(inValue);
        }
    }
}
