//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteColegioSWNet.ServicioMatriculaSW {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class matricula : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private int estadoField;
        
        private System.DateTime fechaFinalField;
        
        private bool fechaFinalFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private System.DateTime fechaInscripcionField;
        
        private bool fechaInscripcionFieldSpecified;
        
        private double notaDefinitivaField;
        
        private string pkEstudianteField;
        
        private int pkMateriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFinal {
            get {
                return this.fechaFinalField;
            }
            set {
                this.fechaFinalField = value;
                this.RaisePropertyChanged("fechaFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinalSpecified {
            get {
                return this.fechaFinalFieldSpecified;
            }
            set {
                this.fechaFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaInscripcion {
            get {
                return this.fechaInscripcionField;
            }
            set {
                this.fechaInscripcionField = value;
                this.RaisePropertyChanged("fechaInscripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified {
            get {
                return this.fechaInscripcionFieldSpecified;
            }
            set {
                this.fechaInscripcionFieldSpecified = value;
                this.RaisePropertyChanged("fechaInscripcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double notaDefinitiva {
            get {
                return this.notaDefinitivaField;
            }
            set {
                this.notaDefinitivaField = value;
                this.RaisePropertyChanged("notaDefinitiva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string pkEstudiante {
            get {
                return this.pkEstudianteField;
            }
            set {
                this.pkEstudianteField = value;
                this.RaisePropertyChanged("pkEstudiante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int pkMateria {
            get {
                return this.pkMateriaField;
            }
            set {
                this.pkMateriaField = value;
                this.RaisePropertyChanged("pkMateria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosWeb/", ConfigurationName="ServicioMatriculaSW.ServicioMatriculaSW")]
    public interface ServicioMatriculaSW {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculas/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasResponse darMatriculas(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculasResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasResponse> darMatriculasAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/borrarMatriculaCodigoRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/borrarMatriculaCodigoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/borrarMatriculaCodigo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoResponse borrarMatriculaCodigo(ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/borrarMatriculaCodigoRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/borrarMatriculaCodigoResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoResponse> borrarMatriculaCodigoAsync(ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/matricularEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/matricularEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/matricularEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteResponse matricularEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/matricularEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/matricularEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteResponse> matricularEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteResponse darMatriculasEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteResponse> darMatriculasEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/actualizarMatriculaRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/actualizarMatriculaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/actualizarMatricula/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaResponse actualizarMatricula(ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/actualizarMatriculaRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/actualizarMatriculaResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaResponse> actualizarMatriculaAsync(ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darPazYSalvoEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darPazYSalvoEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/darPazYSalvoEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteResponse darPazYSalvoEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darPazYSalvoEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darPazYSalvoEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteResponse> darPazYSalvoEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculaCodigoRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculaCodigoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculaCodigo/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoResponse darMatriculaCodigo(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculaCodigoRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculaCodigoResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoResponse> darMatriculaCodigoAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasPorFechaRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculasPorFechaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasPorFecha/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaResponse darMatriculasPorFecha(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasPorFechaRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculasPorFechaResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaResponse> darMatriculasPorFechaAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMateriasPorGradoRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMateriasPorGradoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/darMateriasPorGrado/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoResponse darMateriasPorGrado(ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMateriasPorGradoRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMateriasPorGradoResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoResponse> darMateriasPorGradoAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darPromedioEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darPromedioEstudianteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/darPromedioEstudiante/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteResponse darPromedioEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darPromedioEstudianteRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darPromedioEstudianteResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteResponse> darPromedioEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteGradoRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteGradoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteColegioSWNet.ServicioMatriculaSW.Exception), Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteGrado/Fault/Except" +
            "ion", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoResponse darMatriculasEstudianteGrado(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteGradoRequest", ReplyAction="http://serviciosWeb/ServicioMatriculaSW/darMatriculasEstudianteGradoResponse")]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoResponse> darMatriculasEstudianteGradoAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculas", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculasRequest {
        
        public darMatriculasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculasResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula[] @return;
        
        public darMatriculasResponse() {
        }
        
        public darMatriculasResponse(ClienteColegioSWNet.ServicioMatriculaSW.matricula[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="borrarMatriculaCodigo", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class borrarMatriculaCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public borrarMatriculaCodigoRequest() {
        }
        
        public borrarMatriculaCodigoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="borrarMatriculaCodigoResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class borrarMatriculaCodigoResponse {
        
        public borrarMatriculaCodigoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="matricularEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class matricularEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0;
        
        public matricularEstudianteRequest() {
        }
        
        public matricularEstudianteRequest(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="matricularEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class matricularEstudianteResponse {
        
        public matricularEstudianteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculasEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculasEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public darMatriculasEstudianteRequest() {
        }
        
        public darMatriculasEstudianteRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculasEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculasEstudianteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula[] @return;
        
        public darMatriculasEstudianteResponse() {
        }
        
        public darMatriculasEstudianteResponse(ClienteColegioSWNet.ServicioMatriculaSW.matricula[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarMatricula", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class actualizarMatriculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0;
        
        public actualizarMatriculaRequest() {
        }
        
        public actualizarMatriculaRequest(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarMatriculaResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class actualizarMatriculaResponse {
        
        public actualizarMatriculaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darPazYSalvoEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darPazYSalvoEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula arg1;
        
        public darPazYSalvoEstudianteRequest() {
        }
        
        public darPazYSalvoEstudianteRequest(int arg0, ClienteColegioSWNet.ServicioMatriculaSW.matricula arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darPazYSalvoEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darPazYSalvoEstudianteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public darPazYSalvoEstudianteResponse() {
        }
        
        public darPazYSalvoEstudianteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculaCodigo", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculaCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public darMatriculaCodigoRequest() {
        }
        
        public darMatriculaCodigoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculaCodigoResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculaCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula @return;
        
        public darMatriculaCodigoResponse() {
        }
        
        public darMatriculaCodigoResponse(ClienteColegioSWNet.ServicioMatriculaSW.matricula @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculasPorFecha", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculasPorFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg0;
        
        public darMatriculasPorFechaRequest() {
        }
        
        public darMatriculasPorFechaRequest(System.DateTime arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculasPorFechaResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculasPorFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula[] @return;
        
        public darMatriculasPorFechaResponse() {
        }
        
        public darMatriculasPorFechaResponse(ClienteColegioSWNet.ServicioMatriculaSW.matricula[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class materia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private int gradoField;
        
        private double intensidadHorariaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int grado {
            get {
                return this.gradoField;
            }
            set {
                this.gradoField = value;
                this.RaisePropertyChanged("grado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double intensidadHoraria {
            get {
                return this.intensidadHorariaField;
            }
            set {
                this.intensidadHorariaField = value;
                this.RaisePropertyChanged("intensidadHoraria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMateriasPorGrado", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMateriasPorGradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public darMateriasPorGradoRequest() {
        }
        
        public darMateriasPorGradoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMateriasPorGradoResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMateriasPorGradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.materia[] @return;
        
        public darMateriasPorGradoResponse() {
        }
        
        public darMateriasPorGradoResponse(ClienteColegioSWNet.ServicioMatriculaSW.materia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darPromedioEstudiante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darPromedioEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0;
        
        public darPromedioEstudianteRequest() {
        }
        
        public darPromedioEstudianteRequest(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darPromedioEstudianteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darPromedioEstudianteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public darPromedioEstudianteResponse() {
        }
        
        public darPromedioEstudianteResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculasEstudianteGrado", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculasEstudianteGradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public darMatriculasEstudianteGradoRequest() {
        }
        
        public darMatriculasEstudianteGradoRequest(string arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="darMatriculasEstudianteGradoResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class darMatriculasEstudianteGradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula[] @return;
        
        public darMatriculasEstudianteGradoResponse() {
        }
        
        public darMatriculasEstudianteGradoResponse(ClienteColegioSWNet.ServicioMatriculaSW.matricula[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioMatriculaSWChannel : ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMatriculaSWClient : System.ServiceModel.ClientBase<ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW>, ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW {
        
        public ServicioMatriculaSWClient() {
        }
        
        public ServicioMatriculaSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMatriculaSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMatriculaSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMatriculaSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculas(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasRequest request) {
            return base.Channel.darMatriculas(request);
        }
        
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula[] darMatriculas() {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasRequest();
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculasAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasRequest request) {
            return base.Channel.darMatriculasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasResponse> darMatriculasAsync() {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasRequest();
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.borrarMatriculaCodigo(ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoRequest request) {
            return base.Channel.borrarMatriculaCodigo(request);
        }
        
        public void borrarMatriculaCodigo(int arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).borrarMatriculaCodigo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.borrarMatriculaCodigoAsync(ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoRequest request) {
            return base.Channel.borrarMatriculaCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoResponse> borrarMatriculaCodigoAsync(int arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.borrarMatriculaCodigoRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).borrarMatriculaCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.matricularEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteRequest request) {
            return base.Channel.matricularEstudiante(request);
        }
        
        public void matricularEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).matricularEstudiante(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.matricularEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteRequest request) {
            return base.Channel.matricularEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteResponse> matricularEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.matricularEstudianteRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).matricularEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculasEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteRequest request) {
            return base.Channel.darMatriculasEstudiante(request);
        }
        
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula[] darMatriculasEstudiante(string arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculasEstudiante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculasEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteRequest request) {
            return base.Channel.darMatriculasEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteResponse> darMatriculasEstudianteAsync(string arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculasEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.actualizarMatricula(ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaRequest request) {
            return base.Channel.actualizarMatricula(request);
        }
        
        public void actualizarMatricula(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).actualizarMatricula(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.actualizarMatriculaAsync(ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaRequest request) {
            return base.Channel.actualizarMatriculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaResponse> actualizarMatriculaAsync(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.actualizarMatriculaRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).actualizarMatriculaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darPazYSalvoEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteRequest request) {
            return base.Channel.darPazYSalvoEstudiante(request);
        }
        
        public bool darPazYSalvoEstudiante(int arg0, ClienteColegioSWNet.ServicioMatriculaSW.matricula arg1) {
            ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darPazYSalvoEstudiante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darPazYSalvoEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteRequest request) {
            return base.Channel.darPazYSalvoEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteResponse> darPazYSalvoEstudianteAsync(int arg0, ClienteColegioSWNet.ServicioMatriculaSW.matricula arg1) {
            ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darPazYSalvoEstudianteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darPazYSalvoEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculaCodigo(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoRequest request) {
            return base.Channel.darMatriculaCodigo(request);
        }
        
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula darMatriculaCodigo(int arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculaCodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculaCodigoAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoRequest request) {
            return base.Channel.darMatriculaCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoResponse> darMatriculaCodigoAsync(int arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculaCodigoRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculaCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculasPorFecha(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaRequest request) {
            return base.Channel.darMatriculasPorFecha(request);
        }
        
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula[] darMatriculasPorFecha(System.DateTime arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculasPorFecha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculasPorFechaAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaRequest request) {
            return base.Channel.darMatriculasPorFechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaResponse> darMatriculasPorFechaAsync(System.DateTime arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasPorFechaRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculasPorFechaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMateriasPorGrado(ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoRequest request) {
            return base.Channel.darMateriasPorGrado(request);
        }
        
        public ClienteColegioSWNet.ServicioMatriculaSW.materia[] darMateriasPorGrado(int arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMateriasPorGrado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMateriasPorGradoAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoRequest request) {
            return base.Channel.darMateriasPorGradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoResponse> darMateriasPorGradoAsync(int arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMateriasPorGradoRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMateriasPorGradoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darPromedioEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteRequest request) {
            return base.Channel.darPromedioEstudiante(request);
        }
        
        public double darPromedioEstudiante(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteRequest();
            inValue.arg0 = arg0;
            ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darPromedioEstudiante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darPromedioEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteRequest request) {
            return base.Channel.darPromedioEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteResponse> darPromedioEstudianteAsync(ClienteColegioSWNet.ServicioMatriculaSW.matricula arg0) {
            ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darPromedioEstudianteRequest();
            inValue.arg0 = arg0;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darPromedioEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoResponse ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculasEstudianteGrado(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoRequest request) {
            return base.Channel.darMatriculasEstudianteGrado(request);
        }
        
        public ClienteColegioSWNet.ServicioMatriculaSW.matricula[] darMatriculasEstudianteGrado(string arg0, int arg1) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoResponse retVal = ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculasEstudianteGrado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoResponse> ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW.darMatriculasEstudianteGradoAsync(ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoRequest request) {
            return base.Channel.darMatriculasEstudianteGradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoResponse> darMatriculasEstudianteGradoAsync(string arg0, int arg1) {
            ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoRequest inValue = new ClienteColegioSWNet.ServicioMatriculaSW.darMatriculasEstudianteGradoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteColegioSWNet.ServicioMatriculaSW.ServicioMatriculaSW)(this)).darMatriculasEstudianteGradoAsync(inValue);
        }
    }
}
